language: python
python:
    - "3.5"
    - "nightly"

install:
    - "pip install -r requirements.txt"
    - "pip install pep8"

script:
    - "python -m pep8 */*.py"
    - "python -m unittest discover -p *_test.py -v"
