language: python
python:
    - "3.5"
    - "nightly"

install:
    - "pip install -r requirements.txt"
    - "pip install pycodestyle"

script:
    - "python -m pycodestyle src"
    - "python -m unittest discover -p *_test.py -v"
